server:
  port: 8082
  address: 0.0.0.0
#Matser的ip地址
spring:
  redis:
    host: localhost
    port: 9367
    password:   #如果有密码
    timeout: 1000 #客户端超时时间单位是毫秒 默认是2000
    maxIdle: 300 #最大空闲数
    #连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
    #redis.maxActive=600
    #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
    maxTotal: 1000
    #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
    maxWaitMillis: 1000
    #连接的最小空闲时间 默认1800000毫秒(30分钟)
    minEvictableIdleTimeMillis: 300000
    #每次释放连接的最大数目,默认3
    numTestsPerEvictionRun: 1024
    #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
    timeBetweenEvictionRunsMillis: 30000
    #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    testOnBorrow: true
    #在空闲时检查有效性, 默认false
    testWhileIdle: true

    #redis集群配置
    cluster.nodes: 192.168.177.128:7001,192.168.177.128:7002,192.168.177.128:7003,192.168.177.128:7004,192.168.177.128:7005,192.168.177.128:7006
    cluster.max-redirects: 3

    #哨兵模式
    senHost1: 192.168.177.128
    senPort1: 26379

    #sentinel.host2=172.20.1.231
    #sentinel.port2=26379
